apiVersion: apps/v1
kind: Deployment
metadata:
  name:  spring-rest-crud-api
  labels:
    app:  spring-rest-crud-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  spring-rest-crud-api
  template:
    metadata:
      labels:
        app:  spring-rest-crud-api
    spec:
      containers:
      - name: spring-rest-crud-api
        image:  spring-rest-crud-api:latest
        ports:
        - containerPort: 8080
