apiVersion: v1
kind: Service
metadata:
  name:  spring-rest-crud-api
spec:
  selector:
    app:  spring-rest-crud-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
